apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  ports:
  - name: traefik
    port: 9000
    protocol: TCP
    targetPort: traefik
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
