apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    app: front-traefik
  ports:
  - name: traefik
    port: 9000
    protocol: TCP
    targetPort: traefik
  - name: web
    port: 8000
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 8443
    protocol: TCP
    targetPort: websecure
  - name: dns
    port: 8053
    protocol: UDP
    targetPort: dns
