apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - nfs
  - base/ingress.yaml
  - base/toolbox.yaml
  - base/cluster.yaml
  - base/operator.yaml
  - base/common.yaml
  - base/crds.yaml