apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - base/ingress.yaml


helmCharts:
- name: rook-ceph
  includeCRDs: true
  version: 1.14.2
  releaseName: "rook-ceph-cluster"
  repo: https://charts.rook.io/release
  valuesFile: base/operator-values.yaml
- name: rook-ceph
  includeCRDs: true
  version: 1.14.2
  releaseName: "rook-ceph"
  repo: https://charts.rook.io/release
  valuesFile: base/cluster-values.yaml

