apiVersion: v1
kind: ConfigMap
metadata:
  name: sftpgo
  namespace: sftpgo
data:
  sftpgo.json: |-
    defender:
      enabled: true,
      driver: memory,
      ban_time: 30,
      ban_time_increment: 50,
      threshold: 15,
      score_invalid: 2,
      score_valid: 1,
      score_limit_exceeded: 3,
      score_no_auth: 0,
      observation_time: 30,
      entries_soft_limit: 100,
      entries_hard_limit: 150
    rate_limiters: [
      {
        average: 0,
        period: 1000,
        burst: 1,
        type: 2,
        protocols: [
          SSH,
          FTP,
          DAV,
          HTTP
        ],
        generate_defender_events: false,
        entries_soft_limit: 100,
        entries_hard_limit: 150
      }
    ]
    webdavd:
      bindings: [
        {
          port: 8081,
          address: 0.0.0.0,
          enable_https: false,
        }
      ]
    telemetry:
      bind_port: 10000,
      bind_address: 0.0.0.0,
      enable_profiler: false,
      auth_user_file: ,
      certificate_file: ,
      certificate_key_file: ,
      min_tls_version: 12,
      tls_cipher_suites: [],
      tls_protocols: []