---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sftpgo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sftpgo
    app.kubernetes.io/version: latest
    app: sftpgo
  name: sftpgo
  namespace: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sftpgo
      app.kubernetes.io/name: sftpgo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sftpgo
        app.kubernetes.io/name: sftpgo
    spec:
      containers:
      - args:
        - sftpgo
        - serve
        env:
        - name: SFTPGO_SFTPD__BINDINGS__0__PORT
          value: "2022"
        - name: SFTPGO_HTTPD__BINDINGS__0__PORT
          value: "8080"
        - name: SFTPGO_TELEMETRY__BIND_PORT
          value: "10000"
        - name: SFTPGO_WEBDAVD__BINDINGS__0__PORT
          value: "8081"
        image: ghcr.io/drakkan/sftpgo:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: telemetry
        name: sftpgo
        ports:
        - containerPort: 2022
          name: sftp
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 10000
          name: telemetry
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: telemetry
        resources: {}
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/sftpgo/sftpgo.json
          name: config
          readOnly: true
          subPath: sftpgo.json
      hostNetwork: false
      securityContext: {}
      serviceAccountName: sftpgo
      volumes:
      - configMap:
          name: sftpgo
        name: config