apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo
spec:
  storageClassName: "rook-cephfs"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consume-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: ""
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: consume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: rook-csi-cephfs-node-user
      # node stage secret namespace where above secret is created
      namespace: rook-ceph
    volumeAttributes:
      # optional file system to be mounted
      # "fsName": "myfs"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "rook-ceph"
      "staticVolume": "true"
      "rootPath": /volumes/csi/paperless/716a7a59-c361-48a1-ae89-f935919f7e59
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: consume
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

