apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: sftpgo
spec:
  ports:
  - appProtocol: sftp-ssh
    name: sftp
    port: 22
    protocol: TCP
    targetPort: sftp
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: webdav
    port: 80
    protocol: TCP
    targetPort: webdav
  - name: telemetry
    port: 10000
    protocol: TCP
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: sftpgo
  type: ClusterIP
