apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
- base/ingress.yaml
# - base/vaultwarden-data-pvc.yaml
- base/deployment.yaml
- base/namespace.yaml
- base/secret-sealed.yaml
- base/service.yaml

components:
  - ../../components/local-region-selector.yaml