apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

namePrefix: front-

components:
  - ../../../components/front-region-selector.yaml

resources:
  - ../base


patches:
  - path: patches/traefik-service-patch.yaml
  - path: patches/traefik-deployment-patch.yaml
