apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: traefik
  name: treafik-pvc
  namespace: treafik
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi