apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
type: Opaque
stringData:
  username: steffen
  password: AZt6fd3pG5BD94jY
