apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - base/traefik-RBAC.yaml
# - base/traefik-clusterrole.yaml
# - base/traefik-crds.yaml
# - base/traefik-dashboard-ingress.yaml
# - base/traefik-service-account.yaml
- base/argo-cd-ui-ingress.yaml

generators:
- base/traefik-helm-chart.yaml

