apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
- base/argo-cd-ui-ingress.yaml

helmCharts:
- name: traefik/traefik
  includeCRDs: true
  # version: 26.1.0
  repo: https://traefik.github.io/charts
  valuesFile: base/values.yaml
