apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - base/traefik-middleware-default-headers.yaml
  - base/traefik-adguard-service-udp-dns,yaml

helmCharts:
- name: traefik
  includeCRDs: true
  version: 26.1.0
  releaseName: lcl
  repo: https://traefik.github.io/charts
  valuesFile: base/values.yaml
