apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
  namespace: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - name: emby
        image: emby/embyserver:latest
        ports:
        - name: http
          containerPort: 8096
        - name: https
          containerPort: 8920
        - name: http-front
          containerPort: 8080
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /mnt/share_movie
          name: media
          subPath: movie
        - mountPath: /mnt/share_tvshow
          name: media
          subPath: tvshow
        - mountPath: /mnt/share_anime
          name: media
          subPath: anime
        - mountPath: /mnt/share_music
          name: media
          subPath: music
        resources: {}
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 8096
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /web/index.html
            port: 8096
          timeoutSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
          readOnly: false
      - name: media
        nfs:
          server: 192.168.178.4
          path: /mnt/media
