apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emby
  namespace: emby
spec:
  entryPoints:
    - websecure-local
  tls: {}
  routes:
  - match: Host(`emby.steffenillium.de`)
    kind: Rule
    services:
    - name: emby
      port: http
