apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: emby
  sessionAffinity: None
