apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  ports:
    - name: web
      port: 8400
      targetPort: 3000
    - name: ssh
      port: 8422
      targetPort: 22
  selector:
    app: gitea
status:
  loadBalancer: {}
