apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:latest
          name: gitea           
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: gitea-data-pvc
      restartPolicy: Always
      volumes:
        - name: gitea-data-pvc
          persistentVolumeClaim:
            claimName: gitea-data-pvc
