apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    app: gitea
status:
  loadBalancer: {}
