{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ionos-secret",
    "namespace": "kube-system",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ionos-secret",
        "namespace": "kube-system",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/namespace-wide": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "PREFIX": "AgAwGQfuVrLhAGz/9GMzSOPAdKrcJ+nvmEGyXj1v2TycqaQFxSsLdXIZrXnlWCbxwFPOQqOxX3CA3R/bZu797I/iVj8bidXn4tZTUxfvk9DQS8oc4x8JRIDKyian8oa7oqJSEHdqNYPzvulnwTiqvJA3Yzv5aRWJJL1F4gXiyzLE+iQADa/bE8b5eH6OA/hcK0oahGl6pt4zyoMAOZTrNABnAxaOTZnRUSghVnuwJYm2afWG3M4AwHd/hquWyqvLRh4opa89q9+S6X8bBlKLPcvpsNZG7bQsjsp0U1VFrLX0+9MzsON6Dv6EA+Al5raom0m4jHT+5a9cNyU7RZEhbx+KfO7xxZX+8CZy5ngRln7nFi/1tbFLmhXwgxYeGSl0gSGnzvR2iMlQLz+s3yay5R+c9gGOm80/q+HZxnw12Cs5xOR3q5WM6HWYHCymaKoK81xnmbpZnlbHhloBeE0TXH7SUC9I+/y1ZfQUOcnl0Fj3MxeaTkzC35dcsfLb/SqMnDakDVoCV/+A0n0xMpaxX3oje61qFNLBt96p5DC8s7Yo0i+z8ODg8kABzvgbeQiqXTNxow3Hx/DwFeACle3J/66OD1XP3xkt+KCbidkg61bsHBmIXBdjBhF7SIMGD1U8aMTv/w4n74CQgYOXTdclGD73c8FFTBqkYsc09+PHvQQ8i3EojselZIhKT1xqT5sCnuSDpPbmB+aTR7hgUC1zTW5o9cErGuQx7oibKgU1xzjqFA==",
      "SECRET": "AgBcx9BOLNOvvs4GN6VxTR/+5nS2zbERb+yYD3EZhHTiAdST48SDC4lFom2CoRImKLshK2ACHzriYrL1xaW+iK1HMRydRThpEUkgG1sxdynaspVqTA7s63wBjuFaXe87xnmWHWVa5YyyHZRIg0BgbZbR5fUJ1afwFovreqsrns5re1eNJVmh1ZzqoStOBF04ECldyuwn0fuAAp/GiqQyWeQdoOYG8kYnHQifuABFz+7+SAjCSGVpv9v12Xm1I8tmICIE/Znud/LAbyJkrpOFiaru2BXFwhYKdBKID/TWYreK1YLl6uqJ2EJR+FgB7qhsdIlAEhdSLwkPg2o+ZAV/l1/TiKQvcmqudCiTizuwQeUYeFme8IulILHphR+Q1CI3UrrcQS2aGpQ/psvSFvr/9HJTS7EqlRtPqfZKBHMcObBHrc2DZpMhWJeP9I6bb7KzjHIWIgeLn9s3E3ZTdCkbPKkBzFkdAG6hkTWmlpqEPFgGIcaTXnrymebMptmH2a/5m3XZYmbrALk98UXT881eHh1NFGy9t7xBx4pCJF72rzQLsaDGvKqByt/n90ycD69F/fb8Tm1IZElog55ib39MWIJ1aVHBosEUfS1zN/ttqIaiT+UxmMo0TzWPm5ww9TyGyEXMXs3fJhKa2uelVYHYBahR/pwakoem/V1BMxufxLnlnyqlUX00c/6JMo5e0D+Tp5HXgkVpZiVkypWONPeQnK1IAugs5sbWtPinFx5ZECal6JwUqOG0m9p7gEl4eBlqfZIcsDXeXI1VucM8lZNltq71wvFJ1NcWbB6qM1BLhAjGh4M4qz8W7w=="
    }
  }
}
