apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - dns-issuer.yaml
  - ionos-secret-sealed.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  version: 1.14.4
  releaseName: "cert-manager"
  repo: https://charts.jetstack.io
  # valuesFile: values.yaml
