apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi