apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default

spec:
  secretName: letsencrypt-ionos-key
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  defaultGeneratedCert:
    resolver: default
    domain:
      main: steffenillium.de
      sans:
        - '*.steffenillium.de'
