apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error
  namespace: traefik
spec:
  errors:
    status:
      - "400-599"
    service: 
      name: traefik-front
      port: 443
    query: "https://steffenillium.de/404.html"
