apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: no-auth-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: ratelimit
      - name: compress
      # - name: error
      # - name: xfwd-exclude
      - name: default-headers
      
