apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: no-auth-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - rate_limit
      - compress
      - error
      - xfwd_exclude
      - default-headers
      
