apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: no-auth-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: rate_limit
      - name: compress
      - name: error
      - name: xfwd_exclude
      - name: default-headers
      
