# Exclude from `X-Forwarded-For`
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: xfwd-exclude
  namespace: traefik
spec:
  ipAllowList:
    ipStrategy:
      sourceRange:
        - 0.0.0.0/0
      excludedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/8
