apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure-local
  tls: {}
  routes:
  - match: Host(`rook.steffenillium.de`)
    kind: Rule
    services:
    - name: rook-ceph-mgr-dashboard
      port: 7000
