apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ebs
spec:
  entryPoints:
    - web-local
    - websecure-local
  routes:
  - match: Host(`ebs.steffenillium.de`)
    kind: Rule
    services:
    - name: console
      port: http
