apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- networking
- base/paperless-secret-sealed.yaml
- base/webserver-ingress.yaml
- base/webserver-service.yaml
- base/paperless.yaml
- base/paperless-namespace.yaml

components:
  - ../../components/local-region-selector.yaml
