apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/pvc.yaml
- base/paperless-secret-sealed.yaml
- base/ingress.yaml
- base/paperless-service.yaml
- base/deployment.yaml
- base/namespace.yaml

components:
  - ../../components/local-region-selector.yaml
