apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/smb-ingress.yaml
- base/smb-service.yaml
- base/smb.yaml
- base/paperless-secret-sealed.yaml
- base/webserver-ingress.yaml
- base/webserver-service.yaml
- base/paperless.yaml
- base/shared-smb-pvc.yaml
- base/paperless-namespace.yaml

components:
  - ../../components/local-region-selector.yaml
