apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/ftp-service.yaml
- base/ftp.yaml
- base/paperless-broker.yaml
- base/paperless-db.yaml
- base/paperless-secret-sealed.yaml
- base/webserver-service.yaml
- base/webserver.yaml
# - base/webserver-pvc.yaml
- base/shared-ftp-pvc
# - base/paperless-db-pvc.yaml
- base/paperless-namespace.yaml

components:
  - ../../components/local-region-selector.yaml
