apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/ftp-service.yaml
- base/ftp.yaml
- base/paperless-secret-sealed.yaml
- base/webserver-ingress.yaml
- base/webserver-service.yaml
- base/single-pod-deployment.yaml
- base/shared-ftp-pvc.yaml
- base/paperless-namespace.yaml

components:
  - ../../components/local-region-selector.yaml
