apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/pvc.yaml
- base/secret-sealed.yaml
- base/ingress.yaml
- base/app-service.yaml
- base/database-service.yaml
- base/app.yaml
- base/redis.yaml
- base/redis-service.yaml
- base/database.yaml
- base/namespace.yaml

components:
  - ../../components/local-region-selector.yaml
