apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
- base/paperless-secret-sealed.yaml
- base/paperless-ingress.yaml
- base/paperless-service.yaml
- base/paperless.yaml
- base/paperless-namespace.yaml

components:
  - ../../components/local-region-selector.yaml
