apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cert-manager-ui
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`cert-manager.steffenillium.de`)
    kind: Rule
    services:
    - name: lcl-cert-manager
      kind: Service
      port: 443
