apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: steffenillium-de
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  dnsNames:
    - '*.steffenillium.de'
  issuerRef:
    name: letsencrypt-ionos-staging
  secretName: default-tls