apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voice
  name: voice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice
  template:
    metadata:
      labels:
        app: voice
    spec:
      containers:
        - image: lscr.io/linuxserver/piper:latest
          name: piper
          env:
            - name: TZ
              value: Europe/Berlin
            - name: PIPER_VOICE
              value: en_US-hfc_female-medium
          ports:
            - name: piper
              containerPort: 10200
              protocol: TCP
          resources: {}
        - image: linuxserver/faster-whisper:latest
          name: whisper
          env:
            - name: TZ
              value: Europe/Berlin
            - name: WHISPER_MODEL
              value: large-v3
          ports:
            - name: whisper
              containerPort: 10300
              protocol: TCP
          resources: {}
      restartPolicy: Always
