apiVersion: v1
kind: Service
metadata:
  labels:
    app: voice
  name: voice
spec:
  ports:
    - name: piper
      port: 10200
      targetPort: piper
    - name: whisper
      port: 10300
      targetPort: whisper
  selector:
    app: voice
  type: LoadBalancer
