apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
- name: sealed-secrets
  includeCRDs: true
  version: 2.15.2
  repo: https://bitnami-labs.github.io/sealed-secrets
  # valuesFile: base/values.yaml
