apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - base/nextcloud-ingress.yaml
  - base/nextcloud-admin-sealed.yaml
  - base/nextcloud-namespace.yaml

helmCharts:
- name: nextcloud
  includeCRDs: true
  version: 4.6.4
  repo: https://nextcloud.github.io/helm/
  valuesFile: base/values.yaml
  releaseName: lcl

components:
  - ../../components/local-region-selector.yaml
