apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: smb-ingress-udp138
  labels:
    expose: "false"
    local: "true"
  namespace: paperless
spec:
  entryPoints:
    - smb-udp138
  routes:
  - services:
    - name: smb-server-service-udp138
      port: 138