apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
type: Opaque
stringData:
  SECRET_KEY: "8SV6jGmelqEWcXxtYbZoF+K7n98L1xVECw0Fo5RGwraNRpww"
  AUTHENTIK_POSTGRESQL__PASSWORD: "1Ltx2rqeZ4ycvwVBXgJZC62s5bijQTIkd2mCqwX6kHNnjG1FK4"
  AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql.authentik.svn.cluster.local"
  POSTGRES_PASSWORD: "1Ltx2rqeZ4ycvwVBXgJZC62s5bijQTIkd2mCqwX6kHNnjG1FK4"
  AUTHENTIK_EMAIL__USERNAME: "steffen.illium@gmail.com"
  AUTHENTIK_EMAIL__PASSWORD: "dofj rqop lazo lznx"
  AUTHENTIK_EMAIL__HOST: "smtp.gmail.com"
