authentik:
    error_reporting:
        enabled: false

# add this block under the `authentik:` block in your values.yaml file
# authentik:
email:
    port: 587
    # -- Enable either use_tls or use_ssl. They can't be enabled at the same time.
    use_tls: true
    # -- Enable either use_tls or use_ssl. They can't be enabled at the same time.
    use_ssl: false
    # -- Connection timeout in seconds
    timeout: 30
    # -- Email 'from' address can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
    from: "authentik@steffenillium.de"


global:
    envFrom:
      - secretRef:
          name: authentik-secret

server:
    ingress:
        enabled: false

postgresql:
    enabled: true
    primary:
        persistence:
            enabled: true
            storageClass: local-path


redis:
    enabled: true
    persistence:
        enabled: false