apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: external
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.3  # static IP pre-allocated.
  ports:
    - port: 80
      name: http
    - port: 443
      name: https