apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assitant-ingress
  namespace: external
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`home.steffenillium.de`)
    kind: Rule
    services:
    - name: home-assistant-service
      port: 80

