apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: traefik
spec:
  entryPoints:
    - websecure-front
    - web-local
    - websecure-local
  routes:
  - match: Host(`home.steffenillium.de`)
    kind: Rule
    services:
    - name: home-assistant
      port: http

