apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

components:
  - ../../components/front-region-selector.yaml

resources:
  - base/authentik-secret-sealed.yaml
  - base/authentik-namespace.yaml
  - base/authentik-service.yaml

helmCharts:
- name: authentik
  includeCRDs: true
  version: 2024.2.2
  releaseName: "authentik"
  repo: https://charts.goauthentik.io
  valuesFile: base/values.yaml
