apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml

helmCharts:
- name: prometheus
  includeCRDs: true
  version: 25.20.1
  releaseName: "prometheus"
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
