apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- nextcloud.yaml
- service.yaml
- ingress.yaml
- middleware.yaml
- secret-sealed.yaml
- namespace.yaml
