apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- nextcloud.yaml
# - nextcloud-app-pvc.yaml
- service.yaml
# - nextcloud-db-pvc
- ingress.yaml
- secret-sealed.yaml
- namespace.yaml
