apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- app.yaml
- redis.yaml
- database.yaml
- pvc.yaml
- app-service.yaml
- database-service.yaml
- redis-service.yaml
- ingress.yaml
- middleware.yaml
- secret-sealed.yaml
- namespace.yaml
