apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-db-pvc
  name: nextcloud-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
