ingress:
  enabled: false

phpClientHttpsFix:
  enabled: true
  protocol: http

nextcloud:
  host: newcloud.steffenillium.de
  ## Use an existing secret
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password
    smtpUsernameKey: smtpUsername
    smtpPasswordKey: smtpPassword
    smtpHostKey: smtpHost
  mail:
    enabled: true
    fromAddress: newcloud
    domain: steffenillium.de
    smtp:
      secure: ssl
      port: 465
      authtype: LOGIN
  

internalDatabase:
  enabled: true
  name: nextcloud

cronjob:
  enabled: true

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 150Gi
