apiVersion: v1
kind: Service
metadata:
 name: rook-ceph-nfs-load-balancer
 namespace: rook-ceph
 annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.178.100
spec:
 ports: 
   - name: nfs
     port: 2049
 type: LoadBalancer
 externalTrafficPolicy: Local
 selector:
   app: rook-ceph-nfs
   ceph_nfs: rooknfs
   instance: a