apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
  namespace: traefik
  labels:
    expose: "true"
    local: "true"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`home.steffenillium.de`)
    kind: Rule
    services:
    - name: home-assistant-service
      port: http

