apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  project: default
  source:
    path: apps/nextcloud
    repoURL: https://github.com/illiumst/kubedeploy.git
    targetRevision: HEAD
  syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
      - CreateNamespace=true