apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  project: default
  source:
    path: apps/gitea
    repoURL: https://github.com/illiumst/kubedeploy.git
    targetRevision: HEAD
  syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
      - CreateNamespace=true