apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: website
  project: default
  source:
    path: projects/website
    repoURL: https://github.com/illiumst/kubedeploy.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
