apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik

spec:
  defaultGeneratedCert:
    resolver: default
    domain:
      main: steffenillium.de
      sans:
        - "*.steffenillium.de"