apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  storageClassName: "rook-cephfs"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
