apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret-sealed
  namespace: vaultwarden
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: true
type: Opaque
stringData:
  key: val
  
