apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vaultwarden-data-pvc
  name: vaultwarden-data-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
