apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: rook-csi-cephfs-node
      # node stage secret namespace where above secret is created
      namespace: rook-ceph
    volumeAttributes:
      # optional file system to be mounted
      "fsName": "myfs"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "99c133b4-bd71-4eb9-9c00-ced76abf2a40"
      "staticVolume": "true"
      "rootPath": "/volumes/csi/vaultwarden/5d18ebea-40f6-4de5-8691-5c4fcfd6768e"
      # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: vaultwarden
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "rook-cephfs"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  storageClassName: "rook-cephfs"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: vaultwarden
