apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-ingress
  namespace: vaultwarden
  labels:
    expose: "true"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`vault.steffenillium.de`)
    kind: Rule
    services:
    - name: vaultwarden
      port: 80
