apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservices
  name: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - args:
            - start.sh
            - microservices
          envFrom:
            - secretRef:
                name: immich-secret
          image: ghcr.io/immich-app/immich-server:release
          name: microservices
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: photos
              subPath: upload
            - mountPath: /usr/src/app/external
              name: photos
      restartPolicy: Always
      volumes:
        - name: photos
          nfs:
            server: 192.168.178.4
            path: /mnt/photos