apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

components:
  - ../../components/local-region-selector.yaml

resources:
- base/ui-ingress.yaml
- https://github.com/minio/operator