apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/ingress.yaml


helmCharts:
- name: rook-ceph
  includeCRDs: true
  version: 1.14.2
  releaseName: "rook-ceph"
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
