apiVersion: v1
kind: Service
metadata:
  labels:
    app: machine-learning
  name: machine-learning
spec:
  ports:
    - name: "http"
      port: 3003
      targetPort: http
  selector:
    app: machine-learning