apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
    - name: "server"
      port: 3001
      targetPort: server
    - name: "microservices"
      port: 3002
      targetPort: microservices
  selector:
    app: server