apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
    - name: "http"
      port: 3001
      targetPort: 3001
    - name: "http"
      port: 3002
      targetPort: 3002
  selector:
    app: server