apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fritz-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure-local
  routes:
  - match: Host(`fritz.steffenillium.de`)
    kind: Rule
    tls: {}
    services:
    - name: fritz-service
      port: http
