apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- base/longhorn-ui-ingress.yaml

helmCharts:
- name: longhorn
  includeCRDs: true
  version: 1.6.0
  repo: https://charts.longhorn.io
  valuesFile: base/values.yaml

patches:
- path: patches/nodeselector.yaml
  target:
    kind: (StatefulSet|Deployment|Job)
- path: patches/podselector.yaml
  target:
    kind: Pod

