apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- base/longhorn-ui-ingress.yaml

helmCharts:
- name: longhorn
  includeCRDs: true
  version: 1.6.0
  releaseName: longhorn
  repo: https://charts.longhorn.io
  valuesFile: base/values.yaml
