apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

resources:
- base/adguard-cm.yaml
- base/adguard-deployment.yaml
- base/adguard-ingress.yaml
- base/adguard-namespace.yaml
- base/adguard-pvc.yaml
- base/adguard-service.yaml
