apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless
  name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/paperless-ngx:latest
          name: paperless
          ports:
            - name: http 
              containerPort: 8000
              protocol: TCP
          resources:
            limits: {}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: paperless-pvc
              subPath: 716a7a59-c361-48a1-ae89-f935919f7e59/app
            - mountPath: /usr/src/paperless/media
              name: paperless-media
            - mountPath: /usr/src/paperless/consume
              name: paperless-pvc
              subPath: 716a7a59-c361-48a1-ae89-f935919f7e59/consume
          env:
            - name: DEBUG
              value: "false"
            - name: PAPERLESS_ALLOWED_HOSTS
              value: steffenillium.de,localhost
            - name: PAPERLESS_CONSUMER_POLLING
              value: "20"
            - name: PAPERLESS_CONSUMER_RECURSIVE
              value: "true"
            - name: PAPERLESS_CORS_ALLOWED_HOSTS
              value: http://localhost:8000
            - name: PAPERLESS_DBHOST
              value: localhost
            - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
              value: "true"
            - name: PAPERLESS_OCR_LANGUAGE
              value: deu
            - name: PAPERLESS_OCR_LANGUAGES
              value: eng deu
            - name: PAPERLESS_OCR_ROTATE_PAGES
              value: "true"
            - name: PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD
              value: "10"
            - name: PAPERLESS_DBHOST
              value: database
            - name: PAPERLESS_REDIS
              value: redis://redis:6379
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Berlin
            - name: PAPERLESS_URL
              value: https://documents.steffenillium.de
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_SECRET_KEY
      restartPolicy: Always
      volumes:
        - name: paperless-pvc
          persistentVolumeClaim:
            claimName: paperless-pvc
        - name:  paperless-media
          nfs:
            server: 192.168.178.4
            path: /mnt/storage/service/paperless/media
            readOnly: false
