apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      labels:
        app: ftp-server
    spec:
      containers:
      - name: ftp-server-container
        image: fauria/vsftpd
        ports:
        - containerPort: 21
          protocol: TCP
          name: ftp-server
        env:
        - name: FTP_USER
          valueFrom: 
            secretKeyRef:
              name: paperless-secret
              key: FTP_USER
        - name: FTP_PASS
          valueFrom: 
            secretKeyRef:
              name: paperless-secret
              key: FTP_PASS
        volumeMounts:
          - mountPath: "/home/vsftpd"
            name: shared-ftp-pvc
        resources: {}
      volumes:
        - name: shared-ftp-pvc
          persistentVolumeClaim:
            claimName: shared-ftp-pvc
