apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - websecure-local
  tls: {}
  routes:
  - match: Host(`documents.steffenillium.de`)
    kind: Rule
    services:
    - name: paperless
      port: http
