apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless-webserver
  name: paperless-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless-webserver
    spec:
      containers:
        - image: docker.io/library/postgres:13
          name: paperless-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: paperless-pvc
              subPath: pg-data
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: paperless
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: POSTGRES_PASSWORD
        - image: ghcr.io/paperless-ngx/paperless-ngx:latest
          name: paperless-webserver
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: paperless-pvc
              subPath: app
            - mountPath: /usr/src/paperless/media
              name: paperless-pvc
              subPath: media
            - mountPath: /usr/src/paperless/consume
              name: paperless-pvc
              subPath: consume
          env:
            - name: DEBUG
              value: "false"
            - name: PAPERLESS_ALLOWED_HOSTS
              value: steffenillium.de,localhost
            - name: PAPERLESS_CONSUMER_RECURSIVE
              value: "true"
            - name: PAPERLESS_CORS_ALLOWED_HOSTS
              value: http://localhost:8000
            - name: PAPERLESS_DBHOST
              value: localhost
            - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
              value: "true"
            - name: PAPERLESS_OCR_LANGUAGE
              value: deu
            - name: PAPERLESS_OCR_LANGUAGES
              value: eng deu
            - name: PAPERLESS_OCR_ROTATE_PAGES
              value: "true"
            - name: PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD
              value: "10"
            - name: PAPERLESS_REDIS
              value: redis://localhost:6379
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Berlin
            - name: PAPERLESS_URL
              value: https://documents.steffenillium.de
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_SECRET_KEY
        - image: docker.io/library/redis:7
          name: paperless-broker
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
      volumes:
        - name: paperless-pvc
          nfs:
            server: 192.168.178.4
            path: /mnt/storage/service/paperless
            readOnly: false
