apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: paperless-db-pvc
  name: paperless-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
