apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shared-smb-pvc
  name: shared-smb-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
