apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: paperless-webserver-pvc
  name: paperless-webserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
