apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: GHCR.io
      prefix: ghcr.io
      api_url: hhttps://ghcr.io/v2
      credentials: pullsecret:argocd/argo-cd-ghcr-secret
