apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-app-pvc
  name: nextcloud-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
status: {}
