apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wgui
  namespace: traefik
spec:
  entryPoints:
    - websecure-local
  routes:
  - match: Host(`wgui.steffenillium.de`)
    kind: Rule
    tls: {}
    services:
    - name: wgui
      port: http

