apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fritz-ingress
  namespace: traefik
  labels:
    expose: "false"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`fritz.steffenillium.de`)
    kind: Rule
    services:
    - name: fritz-service
      port: http

