apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# - base/argo-cd-ui-ingress.yaml
resources:
# Base functionality
- base/argocd-server-service.yaml
- base/argo-cd-k-with-helm.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/argo-cd-namespace.yaml

patches:
- path: patches/argocd-server-service.yaml
- path: patches/argocd-cm-patch.yaml
- path: patches/argocd-cmd-params-cm.yaml
- path: patches/nodeselector.yaml
  target:
    kind: (StatefulSet|Deployment|Job)
