apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

components:
  - ../../components/local-region-selector.yaml

resources:
# Applications
- applications
# Base functionality
- base/argo-cd-k-with-helm.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/argo-cd-namespace.yaml

patches:
  - path: patches/argocd-server-service.yaml
  - path: patches/argocd-cm-patch.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --interval=60m
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-image-updater