apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`longhorn.steffenillium.de`)
    kind: Rule
    services:
    - name: ui
      port: 80
  tls:
    certResolver: default
