apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  labels:
    local: "true"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`longhorn.steffenillium.de`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
