apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-ui
  namespace: adguard
  labels:
    expose: "true"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`adguard.steffenillium.de`) || Host(`dns.steffenillium.de`)
    kind: Rule
    services:
    - name: adguard-service
      port: 80

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-ui-init
  namespace: adguard
  labels:
    expose: "true"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`adguard-init.steffenillium.de`)
    kind: Rule
    services:
    - name: adguard-service
      port: 3000
