apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authentik-redis-master
spec:
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: authentik
        app.kubernetes.io/name: redis
      name: redis-data
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi