apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ui
  namespace: argocd
  labels:
    expose: "false"
    local: "true"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`argocd.steffenillium.de`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
