apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ui
  namespace: argocd
spec:
  entryPoints:
  - websecure-local
  routes:
  - match: Host(`argocd.steffenillium.de`)
    kind: Rule
    tls: {}
    services:
    - name: argocd-server
      port: 80
