apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
spec:
  entryPoints:
    - websecure-local
  tls: {}
  routes:
  - match: Host(`photos.steffenillium.de`)
    kind: Rule
    services:
    - name: server
      port: server
