apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Shared resouces for reuseability in multiple overlays.
components:
  - crds


resources:
# Deployment
- deployment-traefik.yaml
# Objects
- traefik-middleware-default-headers.yaml
- traefik-service.yaml
- networking
- security


