apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Deployment
- deployment-traefik.yaml
# Objects
- traefik-adguard-service-udp-dns.yaml
- traefik-middleware-default-headers.yaml
- traefik-service.yaml
- foreign
- networking
- security


