apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "rook-cephfs"
  resources:
    requests:
      storage: 500 Mi