apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  loadBalancerIP: 192.168.178.102
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
  selector:
    app.kubernetes.io/instance: lcl-default
    app.kubernetes.io/name: traefik
  type: LoadBalancer
