apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer

  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
    nodeport: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
    nodeport: 443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
    nodeport: 53
  - name: traefik
    port: 9000
    protocol: TCP
    targetPort: traefik
    nodeport: 9000
