apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik
name: traefik
namespace: traefik
releaseName: latest
repo: https://traefik.github.io/charts
valuesFile: base/values.yaml
