apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik
name: traefik
namespace: traefik
releaseName: 26.1.0
repo: https://traefik.github.io/charts
valuesFile: base/values.yaml
