apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - wildcard-cert.yaml
  - dns-issuer.yaml
  - ionos-secret-sealed.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
  - namespace.yaml

helmCharts:
- name: cert-manager
  includeCRDs: false
  version: 1.14.4
  releaseName: "cert-manager"
  repo: https://charts.jetstack.io
  valuesFile: values.yaml

transformers:
  - patches/annotation-transfom.yaml
