apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - dns-issuer.yaml
  - ionos-secret-sealed.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
  - namespace.yaml

transformers:
  - patches/annotation-transfom.yaml
