apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: cert-manager

components:
  - ../../components/local-region-selector.yaml

resources:
  - wildcard-cert.yaml
  - dns-issuer.yaml
  - ionos-secret-sealed.yaml
  # - additional-roles.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
  - namespace.yaml

helmCharts:
- name: "cert-manager-lego-webhook"
  includeCRDs: false
  version: 1.0.1
  releaseName: "cert-manager-lego-webhook"
  repo: https://yxwuxuanl.github.io/cert-manager-lego-webhook/
  valuesFile: values-lego.yaml
- name: "cert-manager"
  includeCRDs: false
  version: 1.14.4
  releaseName: "cert-manager"
  repo: https://charts.jetstack.io
  valuesFile: values.yaml

transformers:
  - patches/annotation-transfom.yaml
  - patches/annotation-transfom-api.yaml
