global:
  leaderElection:
    namespace: cert-manager

webhook:
  securePort: 10260
  validatingWebhookConfigurationAnnotations: 
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca


clusterResourceNamespace: cert-manager

namespace: cert-manager
