apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik
spec:
  secretName: wildcard-cert
  dnsNames:
    - "steffenillium.de"
    - "*.steffenillium.de"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: steffenillium.de
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: wildcard-cert
  certificates:
    - secretName: wildcard-cert
