apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  loadBalancerIP: 192.168.178.102
  type: LoadBalancer
  selector:
    app: local-traefik
  ports:
  - name: smb137
    port: 137
    protocol: UDP
  - name: smb138
    port: 138
    protocol: UDP
  - name: smb139
    port: 139
    protocol: TCP
  - name: smb445
    port: 445
    protocol: TCP
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: traefik
    port: 9000
    protocol: TCP
    targetPort: 9000