apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  loadBalancerIP: 192.168.178.2
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
