apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.103
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8083
    protocol: TCP
    targetPort: 8083

