apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- base/cert-manager-ui-ingress.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  version: 1.14.4
  repo: https://charts.jetstack.io
  # valuesFile: base/values.yaml

