apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- base/cert-manager-ui-ingress.yaml
- base/ionos-secret-sealed.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: lcl
  version: 1.14.4
  repo: https://charts.jetstack.io
  # valuesFile: base/values.yaml
- name: cert-manager-webhook-ionos
  includeCRDs: true
  releaseName: lcl
  version: 1.0.2
  repo: https://fabmade.github.io/cert-manager-webhook-ionos
  # valuesFile: base/ionos-values.yaml

patches:
- path: patches/nodeselector.yaml
  target:
    kind: (StatefulSet|Deployment|Job)