apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml


helmCharts:
- name: rook-ceph-cluster
  includeCRDs: true
  version: 1.14.2
  releaseName: "rook-ceph-cluster"
  repo: https://charts.rook.io/release
  valuesFile: values.yaml

