apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - base/gitea-ingress.yaml

helmCharts:
- name: gitea
  includeCRDs: true
  version: 10.1.3
  repo: https://dl.gitea.com/charts/
  valuesFile: base/values.yaml
