apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - base/gitea-ingress.yaml
  - base/gitea-service.yaml
  - base/gitea-deployment.yaml
  # - base/gitea-data-pvc.yaml
  - base/gitea-namespace.yaml

patches:
- path: patches/nodeselector.yaml
  target:
    kind: (StatefulSet|Deployment|Job)