apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - base/ingress.yaml
  - base/service.yaml
  - base/deployment.yaml
  - base/pvc.yaml
  - base/namespace.yaml
components:
  - ../../components/local-region-selector.yaml