apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: ghcr.io/illiumst/website:latest
          name: website
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              memory: "1Gi"
      imagePullSecrets:
        - name: ghcr-io-secret
      restartPolicy: Always
