apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-ingress
  namespace: website
spec:
  entryPoints:
    - websecure-front
    - websecure-local
  routes:
  - match: Host(`www.steffenillium.de`) || Host(`steffenillium.de`) 
    kind: Rule
    tls: {}
    services:
    - name: website
      port: http

